<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Domain\Domain.csproj" />
    <ProjectReference Include="..\DTOs\DTOs.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="14.0.0" />
    <PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
    <PackageReference Include="DocumentFormat.OpenXml" Version="3.3.0" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.3.0" />
    <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="7.1.2" />
    <PackageReference Include="MongoDB.Driver" Version="2.28.0" />
    <PackageReference Include="PdfPig" Version="0.1.11" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="7.1.2" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Implementations\Analytics\" />
    <Folder Include="Implementations\CORE\" />
    <Folder Include="Implementations\EVT\" />
    <Folder Include="Implementations\FAC\" />
    <Folder Include="Implementations\FIN\" />
    <Folder Include="Implementations\HR\" />
    <Folder Include="Implementations\RPT\" />
    <Folder Include="Interfaces\CORE\" />
    <Folder Include="Interfaces\EVT\" />
    <Folder Include="Interfaces\FAC\" />
    <Folder Include="Interfaces\FIN\" />
    <Folder Include="Interfaces\HR\" />
    <Folder Include="Interfaces\RPT\" />
  </ItemGroup>

</Project>
